### ISSUE TITLE
Remove duplicate words

### ISSUE THREAD

**Issue by nicolas-raoul** [anki-decks/anki-deck-for-duolingo-chinese#3]
The word "國" was the topic of several rows, probably because it is part of several words.
We should remove all duplicate words. They might occur in separate lessons.

**Comment by leonfox1** [comment]
I removed all duplicates today and I will merge my changes in appx. 12 hours.

**Comment by nicolas-raoul** [comment]
Cool, looking forward to your commit :-)

**Comment by nicolas-raoul** [comment]
Fixed, thanks @leonfox1 ! :-)
